name: zenn_riverpod
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_animated: ^3.0.0
  bubble: ^1.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^0.14.0+1
  pedantic_mono: ^1.14.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true
